language: node_js
node_js:
- "9"

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
    
notifications:
  email:
    recipients:
    - me@joaquin-caro.es
    on_success: change
    on_failure: always