language: node_js
node_js:
- "9"

deploy:
  provider: script
  script: "npm install && npm run release -n"
  

notifications:
  email:
    recipients:
    - me@joaquin-caro.es
    on_success: change
    on_failure: always